name: test

on:
  push:
    paths: test/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v2
          
    - name: cd test make
      run: make -C test
